module.exports = {
  categories: {
    Protein: [
      {
        name: "Whey Protein",
        category: "protein",
        type: "Fast-absorbing",
        price_INR: 1500,
      },
      {
        name: "Casein Protein",
        category: "protein",
        type: "Slow-release",
        price_INR: 2000,
      },
      {
        name: "Pea Protein",
        category: "protein",
        type: "Plant-based",
        price_INR: 1800,
      },
      {
        name: "Rice Protein",
        category: "protein",
        type: "Plant-based",
        price_INR: 1700,
      },
      {
        name: "Hemp Protein",
        category: "protein",
        type: "Plant-based",
        price_INR: 1900,
      },
      {
        name: "Soy Protein",
        category: "protein",
        type: "Plant-based",
        price_INR: 1600,
      },
      {
        name: "Egg White Protein",
        category: "protein",
        type: "Animal-based",
        price_INR: 2200,
      },
      {
        name: "Milk Protein Isolate",
        category: "protein",
        type: "Dairy-based",
        price_INR: 2100,
      },
      {
        name: "Beef Protein",
        category: "protein",
        type: "Animal-based",
        price_INR: 2500,
      },
      {
        name: "Collagen Protein",
        category: "protein",
        type: "Specialized",
        price_INR: 2300,
      },
    ],
    AminoAcids: [
      {
        name: "BCAAs (Leucine)",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1200,
      },
      {
        name: "BCAAs (Isoleucine)",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1200,
      },
      {
        name: "BCAAs (Valine)",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1200,
      },
      {
        name: "Essential Amino Acids (EAAs)",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1500,
      },
      {
        name: "L-Glutamine",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1000,
      },
      {
        name: "Arginine",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1100,
      },
      {
        name: "Citrulline",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1300,
      },
      {
        name: "Methionine",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1400,
      },
      {
        name: "Histidine",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1300,
      },
      {
        name: "Tyrosine",
        category: "AminoAcids",
        type: "Amino Acid",
        price_INR: 1100,
      },
    ],
    Creatine: [
      {
        name: "Creatine Monohydrate",
        category: "Creatine",
        type: "Creatine",
        price_INR: 800,
      },
      {
        name: "Creatine HCL",
        category: "Creatine",
        type: "Creatine",
        price_INR: 900,
      },
      {
        name: "Buffered Creatine",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1000,
      },
      {
        name: "Micronized Creatine",
        category: "Creatine",
        type: "Creatine",
        price_INR: 850,
      },
      {
        name: "Creatine Ethyl Ester",
        category: "Creatine",
        type: "Creatine",
        price_INR: 950,
      },
      {
        name: "Kre-Alkalyn",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1000,
      },
      {
        name: "Creatine Nitrate",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1200,
      },
      {
        name: "Tri-Creatine Malate",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1100,
      },
      {
        name: "Creatine Pyruvate",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1300,
      },
      {
        name: "Liquid Creatine",
        category: "Creatine",
        type: "Creatine",
        price_INR: 1000,
      },
    ],
    PreWorkout: [
      {
        name: "Pre-Workout Blend 1",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 1500,
      },
      {
        name: "Pre-Workout Blend 2",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 1600,
      },
      {
        name: "Pre-Workout Blend 3",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 1700,
      },
      {
        name: "Pre-Workout Blend 4",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 1800,
      },
      {
        name: "Pre-Workout Blend 5",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 1900,
      },
      {
        name: "Pre-Workout Blend 6",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 2000,
      },
      {
        name: "Pre-Workout Blend 7",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 2100,
      },
      {
        name: "Pre-Workout Blend 8",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 2200,
      },
      {
        name: "Pre-Workout Blend 9",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 2300,
      },
      {
        name: "Pre-Workout Blend 10",
        category: "PreWorkout",
        type: "Pre-Workout",
        price_INR: 2400,
      },
    ],
    "Omega-3FattyAcids": [
      {
        name: "Fish Oil Capsules 1",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 800,
      },
      {
        name: "Fish Oil Capsules 2",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 900,
      },
      {
        name: "Fish Oil Capsules 3",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1000,
      },
      {
        name: "Fish Oil Capsules 4",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1100,
      },
      {
        name: "Fish Oil Capsules 5",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1200,
      },
      {
        name: "Fish Oil Capsules 6",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1300,
      },
      {
        name: "Fish Oil Capsules 7",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1400,
      },
      {
        name: "Fish Oil Capsules 8",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1500,
      },
      {
        name: "Fish Oil Capsules 9",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1600,
      },
      {
        name: "Fish Oil Capsules 10",
        category: "Omega-3FattyAcids",
        type: "Omega-3",
        price_INR: 1700,
      },
    ],
    VitaminsandMinerals: [
      {
        name: "Multivitamin 2",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 700,
      },
      {
        name: "Multivitamin 3",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 800,
      },
      {
        name: "Multivitamin 4",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 900,
      },
      {
        name: "Multivitamin 5",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1000,
      },
      {
        name: "Multivitamin 6",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1100,
      },
      {
        name: "Multivitamin 7",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1200,
      },
      {
        name: "Multivitamin 8",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1300,
      },
      {
        name: "Multivitamin 9",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1400,
      },
      {
        name: "Multivitamin 10",
        category: "VitaminsandMinerals",
        type: "Vitamin",
        price_INR: 1500,
      },
    ],
    TestosteroneBoosters: [
      {
        name: "Zinc Supplement 1",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 500,
      },
      {
        name: "Zinc Supplement 2",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 550,
      },
      {
        name: "Zinc Supplement 3",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 600,
      },
      {
        name: "Zinc Supplement 4",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 650,
      },
      {
        name: "Magnesium Supplement 1",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 700,
      },
      {
        name: "Magnesium Supplement 2",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 750,
      },
      {
        name: "Magnesium Supplement 3",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 800,
      },
      {
        name: "Magnesium Supplement 4",
        category: "TestosteroneBoosters",
        type: "Mineral",
        price_INR: 850,
      },
      {
        name: "Vitamin D3 Supplement 1",
        category: "TestosteroneBoosters",
        type: "Vitamin",
        price_INR: 600,
      },
      {
        name: "Vitamin D3 Supplement 2",
        category: "TestosteroneBoosters",
        type: "Vitamin",
        price_INR: 650,
      },
    ],
    Miscellaneous: [
      {
        name: "Beta-Alanine",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1200,
      },
      {
        name: "Glutamine",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1000,
      },
      {
        name: "HMB",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1500,
      },
      {
        name: "L-Carnitine",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1300,
      },
      {
        name: "Taurine",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1100,
      },
      {
        name: "Beta-Hydroxytryptophan",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1400,
      },
      {
        name: "N-Acetyl Cysteine",
        category: "Miscellaneous",
        type: "Amino Acid",
        price_INR: 1600,
      },
      {
        name: "CLA (Conjugated Linoleic Acid)",
        category: "Miscellaneous",
        type: "Fatty Acid",
        price_INR: 1100,
      },
      {
        name: "Green Tea Extract",
        category: "Miscellaneous",
        type: "Antioxidant",
        price_INR: 1200,
      },
      {
        name: "Turmeric Curcumin",
        category: "Miscellaneous",
        type: "Anti-Inflammatory",
        price_INR: 1300,
      },
    ],
  },
};
