module.exports = products = [
  {
    name: "Whey Protein",
    category: "protein",
    type: "Fast-absorbing",
    price_INR: 1500,
    company: "Labrada",
  },
  {
    name: "Casein Protein",
    category: "protein",
    type: "Slow-release",
    price_INR: 2000,
    company: "BSN",
  },
  {
    name: "Pea Protein",
    category: "protein",
    type: "Plant-based",
    price_INR: 1800,
    company: "MyProtein",
  },
  {
    name: "Rice Protein",
    category: "protein",
    type: "Plant-based",
    price_INR: 1700,
    company: "Scivation",
  },
  {
    name: "Hemp Protein",
    category: "protein",
    type: "Plant-based",
    price_INR: 1900,
    company: "Isopure",
  },
  {
    name: "Soy Protein",
    category: "protein",
    type: "Plant-based",
    price_INR: 1600,
    company: "Protein World",
  },
  {
    name: "Egg White Protein",
    category: "protein",
    type: "Animal-based",
    price_INR: 2200,
    company: "Isopure",
  },
  {
    name: "Milk Protein Isolate",
    category: "protein",
    type: "Dairy-based",
    price_INR: 2100,
    company: "Ultimate Nutrition",
  },
  {
    name: "Beef Protein",
    category: "protein",
    type: "Animal-based",
    price_INR: 2500,
    company: "Ultimate Nutrition",
  },
  {
    name: "Collagen Protein",
    category: "protein",
    type: "Specialized",
    price_INR: 2300,
    company: "MyProtein",
  },
  {
    name: "BCAAs (Leucine)",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1200,
    company: "Incredio",
  },
  {
    name: "BCAAs (Isoleucine)",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1200,
    company: "Labrada",
  },
  {
    name: "BCAAs (Valine)",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1200,
    company: "MuscleTech",
  },
  {
    name: "Essential Amino Acids (EAAs)",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1500,
    company: "Dymatize",
  },
  {
    name: "L-Glutamine",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1000,
    company: "MuscleTech",
  },
  {
    name: "Arginine",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1100,
    company: "MuscleTech",
  },
  {
    name: "Citrulline",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1300,
    company: "BSN",
  },
  {
    name: "Methionine",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1400,
    company: "Dymatize",
  },
  {
    name: "Histidine",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1300,
    company: "ABB (American Body Building)",
  },
  {
    name: "Tyrosine",
    category: "AminoAcids",
    type: "Amino Acid",
    price_INR: 1100,
    company: "RSP Nutrition",
  },
  {
    name: "Creatine Monohydrate",
    category: "Creatine",
    type: "Creatine",
    price_INR: 800,
    company: "Ultimate Nutrition",
  },
  {
    name: "Creatine HCL",
    category: "Creatine",
    type: "Creatine",
    price_INR: 900,
    company: "RSP Nutrition",
  },
  {
    name: "Buffered Creatine",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1000,
    company: "MuscleTech",
  },
  {
    name: "Micronized Creatine",
    category: "Creatine",
    type: "Creatine",
    price_INR: 850,
    company: "Optimum Nutrition (ON)",
  },
  {
    name: "Creatine Ethyl Ester",
    category: "Creatine",
    type: "Creatine",
    price_INR: 950,
    company: "Labrada",
  },
  {
    name: "Kre-Alkalyn",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1000,
    company: "Incredio",
  },
  {
    name: "Creatine Nitrate",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1200,
    company: "RSP Nutrition",
  },
  {
    name: "Tri-Creatine Malate",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1100,
    company: "Labrada",
  },
  {
    name: "Creatine Pyruvate",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1300,
    company: "Optimum Nutrition (ON)",
  },
  {
    name: "Liquid Creatine",
    category: "Creatine",
    type: "Creatine",
    price_INR: 1000,
    company: "RSP Nutrition",
  },
  {
    name: "Pre-Workout Blend 1",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 1500,
    company: "Scivation",
  },
  {
    name: "Pre-Workout Blend 2",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 1600,
    company: "MuscleBlaze",
  },
  {
    name: "Pre-Workout Blend 3",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 1700,
    company: "Incredio",
  },
  {
    name: "Pre-Workout Blend 4",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 1800,
    company: "RSP Nutrition",
  },
  {
    name: "Pre-Workout Blend 5",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 1900,
    company: "MuscleTech",
  },
  {
    name: "Pre-Workout Blend 6",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 2000,
    company: "RSP Nutrition",
  },
  {
    name: "Pre-Workout Blend 7",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 2100,
    company: "Big Muscles Nutrition",
  },
  {
    name: "Pre-Workout Blend 8",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 2200,
    company: "BSN",
  },
  {
    name: "Pre-Workout Blend 9",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 2300,
    company: "BSN",
  },
  {
    name: "Pre-Workout Blend 10",
    category: "PreWorkout",
    type: "Pre-Workout",
    price_INR: 2400,
    company: "Ultimate Nutrition",
  },
  {
    name: "Fish Oil Capsules 1",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 800,
    company: "Incredio",
  },
  {
    name: "Fish Oil Capsules 2",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 900,
    company: "Big Muscles Nutrition",
  },
  {
    name: "Fish Oil Capsules 3",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1000,
    company: "BSN",
  },
  {
    name: "Fish Oil Capsules 4",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1100,
    company: "RSP Nutrition",
  },
  {
    name: "Fish Oil Capsules 5",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1200,
    company: "Big Muscles Nutrition",
  },
  {
    name: "Fish Oil Capsules 6",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1300,
    company: "RSP Nutrition",
  },
  {
    name: "Fish Oil Capsules 7",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1400,
    company: "RSP Nutrition",
  },
  {
    name: "Fish Oil Capsules 8",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1500,
    company: "Isopure",
  },
  {
    name: "Fish Oil Capsules 9",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1600,
    company: "Incredio",
  },
  {
    name: "Fish Oil Capsules 10",
    category: "Omega-3FattyAcids",
    type: "Omega-3",
    price_INR: 1700,
    company: "Scivation",
  },
  {
    name: "Multivitamin 2",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 700,
    company: "MuscleTech",
  },
  {
    name: "Multivitamin 3",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 800,
    company: "BSN",
  },
  {
    name: "Multivitamin 4",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 900,
    company: "MyProtein",
  },
  {
    name: "Multivitamin 5",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1000,
    company: "Big Muscles Nutrition",
  },
  {
    name: "Multivitamin 6",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1100,
    company: "Labrada",
  },
  {
    name: "Multivitamin 7",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1200,
    company: "Protein World",
  },
  {
    name: "Multivitamin 8",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1300,
    company: "Scivation",
  },
  {
    name: "Multivitamin 9",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1400,
    company: "MuscleBlaze",
  },
  {
    name: "Multivitamin 10",
    category: "VitaminsandMinerals",
    type: "Vitamin",
    price_INR: 1500,
    company: "Incredio",
  },
  {
    name: "Zinc Supplement 1",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 500,
    company: "RSP Nutrition",
  },
  {
    name: "Zinc Supplement 2",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 550,
    company: "MuscleTech",
  },
  {
    name: "Zinc Supplement 3",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 600,
    company: "BSN",
  },
  {
    name: "Zinc Supplement 4",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 650,
    company: "Incredio",
  },
  {
    name: "Magnesium Supplement 1",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 700,
    company: "Labrada",
  },
  {
    name: "Magnesium Supplement 2",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 750,
    company: "Big Muscles Nutrition",
  },
  {
    name: "Magnesium Supplement 3",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 800,
    company: "ABB (American Body Building)",
  },
  {
    name: "Magnesium Supplement 4",
    category: "TestosteroneBoosters",
    type: "Mineral",
    price_INR: 850,
    company: "Scivation",
  },
  {
    name: "Vitamin D3 Supplement 1",
    category: "TestosteroneBoosters",
    type: "Vitamin",
    price_INR: 600,
    company: "Dymatize",
  },
  {
    name: "Vitamin D3 Supplement 2",
    category: "TestosteroneBoosters",
    type: "Vitamin",
    price_INR: 650,
    company: "Protein World",
  },
  {
    name: "Beta-Alanine",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1200,
    company: "RSP Nutrition",
  },
  {
    name: "Glutamine",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1000,
    company: "RSP Nutrition",
  },
  {
    name: "HMB",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1500,
    company: "BSN",
  },
  {
    name: "L-Carnitine",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1300,
    company: "Incredio",
  },
  {
    name: "Taurine",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1100,
    company: "ABB (American Body Building)",
  },
  {
    name: "Beta-Hydroxytryptophan",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1400,
    company: "Optimum Nutrition (ON)",
  },
  {
    name: "N-Acetyl Cysteine",
    category: "Miscellaneous",
    type: "Amino Acid",
    price_INR: 1600,
    company: "Labrada",
  },
  {
    name: "CLA (Conjugated Linoleic Acid)",
    category: "Miscellaneous",
    type: "Fatty Acid",
    price_INR: 1100,
    company: "Optimum Nutrition (ON)",
  },
  {
    name: "Green Tea Extract",
    category: "Miscellaneous",
    type: "Antioxidant",
    price_INR: 1200,
    company: "Incredio",
  },
  {
    name: "Turmeric Curcumin",
    category: "Miscellaneous",
    type: "Anti-Inflammatory",
    price_INR: 1300,
    company: "Optimum Nutrition (ON)",
  },
];
